-- Phase 10: RAG vector store (pgvector).
--
-- Requires the pgvector extension. On Azure Database for PostgreSQL Flexible
-- Server it must be allow-listed once before this runs:
--   az postgres flexible-server parameter set \
--     --resource-group <rg> --server-name <server> \
--     --name azure.extensions --value vector
--
-- Embeddings are generated by sentence-transformers/all-MiniLM-L6-v2 (384 dims).
-- Ids are application-generated (uuid4) to match the project's no-pgcrypto policy.

create extension if not exists vector;

create table if not exists embeddings (
  id uuid primary key,
  source_type text not null,
  source_id text not null,
  chunk_index integer not null default 0,
  chunk_text text not null,
  embedding vector(384) not null,
  created_at timestamptz not null default now()
);

create index if not exists embeddings_source_idx
  on embeddings (source_type, source_id);

create index if not exists embeddings_vector_idx
  on embeddings using hnsw (embedding vector_cosine_ops);
