begin;

insert into jobs (
  id,
  job_url,
  source,
  company,
  title,
  location,
  employment_type,
  workplace_type,
  date_posted,
  description_text,
  status,
  priority,
  fit_score,
  notes,
  next_action,
  next_action_due
) values
(
  '11111111-1111-4111-8111-111111111111',
  'https://careers.example.com/jobs/ai-automation-engineer',
  'manual',
  'Northwind Labs',
  'AI Automation Engineer',
  'Remote',
  'Full-time',
  'remote',
  '2026-05-14T09:00:00Z',
  'Build internal automations, agent workflows, and cloud integrations using TypeScript, Azure Functions, n8n, and modern LLM tooling.',
  'shortlisted',
  'high',
  91,
  'Strong match for automation and serverless backend work.',
  'Review and tailor resume summary before sending a recruiter outreach draft.',
  '2026-05-17T10:00:00Z'
),
(
  '22222222-2222-4222-8222-222222222222',
  null,
  'manual',
  'AtlasHire',
  'Workflow Operations Analyst',
  'New York, NY',
  'Full-time',
  'hybrid',
  '2026-05-12T13:00:00Z',
  'Own CRM hygiene, reporting, follow-up tracking, and process automation across recruiting operations and hiring workflows.',
  'outreach_drafted',
  'medium',
  82,
  'Good fit for operational rigor and reporting.',
  'Approve the outreach draft and schedule a follow-up reminder.',
  '2026-05-18T16:00:00Z'
),
(
  '33333333-3333-4333-8333-333333333333',
  null,
  'referral',
  'BeaconOps',
  'Solutions Consultant, HR Tech',
  'Austin, TX',
  'Full-time',
  'remote',
  '2026-05-10T17:30:00Z',
  'Support HR customers with demos, discovery, implementation guidance, and workflow recommendations for SaaS operations tooling.',
  'follow_up_due',
  'high',
  79,
  'Worth following up with the referral contact this week.',
  'Send a polite follow-up message and ask whether the referral partner is still available.',
  '2026-05-16T15:00:00Z'
)
on conflict (id) do update set
  job_url = excluded.job_url,
  source = excluded.source,
  company = excluded.company,
  title = excluded.title,
  location = excluded.location,
  employment_type = excluded.employment_type,
  workplace_type = excluded.workplace_type,
  date_posted = excluded.date_posted,
  description_text = excluded.description_text,
  status = excluded.status,
  priority = excluded.priority,
  fit_score = excluded.fit_score,
  notes = excluded.notes,
  next_action = excluded.next_action,
  next_action_due = excluded.next_action_due;

commit;
